# Generated by Django 6.0.5 on 2026-07-10 19:10

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcim', '0234_cablepath_nodes_index'),
        ('extras', '0138_customfieldchoiceset_choice_colors'),
        ('ipam', '0090_vlangroup_recompute_total_vlan_ids'),
        ('tenancy', '0024_default_ordering_indexes'),
        ('users', '0016_default_ordering_indexes'),
        ('virtualization', '0056_virtualmachine_render_config_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZabbixHostGroup',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                (
                    'custom_field_data',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('zid', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                (
                    'owner',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='users.owner',
                    ),
                ),
                (
                    'tags',
                    taggit.managers.TaggableManager(
                        through='extras.TaggedItem', to='extras.Tag'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Host Group',
                'verbose_name_plural': 'Host Groups',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ZabbixHost',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                (
                    'custom_field_data',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('zid', models.PositiveIntegerField(blank=True, null=True)),
                (
                    'assigned_object_id',
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    'assigned_object_type',
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to=models.Q(
                            models.Q(
                                models.Q(('app_label', 'dcim'), ('model', 'device')),
                                models.Q(
                                    ('app_label', 'dcim'),
                                    ('model', 'virtualdevicecontext'),
                                ),
                                models.Q(
                                    ('app_label', 'dcim'), ('model', 'virtualchassis')
                                ),
                                models.Q(
                                    ('app_label', 'virtualization'),
                                    ('model', 'cluster'),
                                ),
                                models.Q(
                                    ('app_label', 'virtualization'),
                                    ('model', 'virtualmachine'),
                                ),
                                _connector='OR',
                            )
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to='contenttypes.contenttype',
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='users.owner',
                    ),
                ),
                (
                    'tags',
                    taggit.managers.TaggableManager(
                        through='extras.TaggedItem', to='extras.Tag'
                    ),
                ),
                (
                    'groups',
                    models.ManyToManyField(
                        related_name='hosts', to='netbox_zabbix.zabbixhostgroup'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Host',
                'verbose_name_plural': 'Hosts',
                'ordering': ('server', 'assigned_object_type', 'assigned_object_id'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ZabbixHostInterface',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                (
                    'custom_field_data',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('zid', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.CharField(max_length=10)),
                ('connection', models.CharField(max_length=3)),
                ('dns', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                (
                    'host',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='interfaces',
                        to='netbox_zabbix.zabbixhost',
                    ),
                ),
                (
                    'ip',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='zabbix_host_interfaces',
                        to='ipam.ipaddress',
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='users.owner',
                    ),
                ),
                (
                    'tags',
                    taggit.managers.TaggableManager(
                        through='extras.TaggedItem', to='extras.Tag'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Host Interface',
                'verbose_name_plural': 'Host Interfaces',
                'ordering': ('host', 'type', 'connection', 'ip', 'id'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ZabbixHostInterfaceSNMP',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                (
                    'custom_field_data',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ('version', models.CharField(max_length=3)),
                ('community', models.CharField(blank=True, max_length=255, null=True)),
                (
                    'context_name',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    'security_name',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    'security_level',
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    'auth_protocol',
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    'auth_passphrase',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    'priv_protocol',
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    'priv_passphrase',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    'interface',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='snmp',
                        to='netbox_zabbix.zabbixhostinterface',
                    ),
                ),
                (
                    'tags',
                    taggit.managers.TaggableManager(
                        through='extras.TaggedItem', to='extras.Tag'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Host Interface SNMP',
                'verbose_name_plural': 'Host Interface SNMP',
                'ordering': ('interface',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ZabbixProxy',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                (
                    'custom_field_data',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('zid', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                (
                    'owner',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='users.owner',
                    ),
                ),
                (
                    'tags',
                    taggit.managers.TaggableManager(
                        through='extras.TaggedItem', to='extras.Tag'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Proxy',
                'verbose_name_plural': 'Proxies',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='zabbixhost',
            name='proxy',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='hosts',
                to='netbox_zabbix.zabbixproxy',
            ),
        ),
        migrations.CreateModel(
            name='ZabbixProxyGroup',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                (
                    'custom_field_data',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('zid', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                (
                    'owner',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='users.owner',
                    ),
                ),
                (
                    'tags',
                    taggit.managers.TaggableManager(
                        through='extras.TaggedItem', to='extras.Tag'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Proxy Group',
                'verbose_name_plural': 'Proxy Groups',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='zabbixproxy',
            name='group',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='proxies',
                to='netbox_zabbix.zabbixproxygroup',
            ),
        ),
        migrations.AddField(
            model_name='zabbixhost',
            name='proxy_group',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='hosts',
                to='netbox_zabbix.zabbixproxygroup',
            ),
        ),
        migrations.CreateModel(
            name='ZabbixServer',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                (
                    'custom_field_data',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=255)),
                ('api_url', models.URLField()),
                ('api_token', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('validate_certificates', models.BooleanField(default=True)),
                (
                    'owner',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='users.owner',
                    ),
                ),
                (
                    'tags',
                    taggit.managers.TaggableManager(
                        through='extras.TaggedItem', to='extras.Tag'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='zabbixproxygroup',
            name='server',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='proxy_groups',
                to='netbox_zabbix.zabbixserver',
            ),
        ),
        migrations.AddField(
            model_name='zabbixproxy',
            name='server',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='proxies',
                to='netbox_zabbix.zabbixserver',
            ),
        ),
        migrations.AddField(
            model_name='zabbixhostgroup',
            name='server',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='host_groups',
                to='netbox_zabbix.zabbixserver',
            ),
        ),
        migrations.AddField(
            model_name='zabbixhost',
            name='server',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='hosts',
                to='netbox_zabbix.zabbixserver',
            ),
        ),
        migrations.CreateModel(
            name='ZabbixTemplate',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                (
                    'custom_field_data',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('zid', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                (
                    'owner',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='users.owner',
                    ),
                ),
                (
                    'server',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='templates',
                        to='netbox_zabbix.zabbixserver',
                    ),
                ),
                (
                    'tags',
                    taggit.managers.TaggableManager(
                        through='extras.TaggedItem', to='extras.Tag'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ('server', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ZabbixHostTemplate',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                (
                    'custom_field_data',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=255)),
                ('managed', models.BooleanField(default=True)),
                (
                    'cluster_groups',
                    models.ManyToManyField(
                        related_name='host_templates', to='virtualization.clustergroup'
                    ),
                ),
                (
                    'cluster_types',
                    models.ManyToManyField(
                        related_name='host_templates', to='virtualization.clustertype'
                    ),
                ),
                (
                    'clusters',
                    models.ManyToManyField(
                        related_name='host_templates', to='virtualization.cluster'
                    ),
                ),
                (
                    'device_types',
                    models.ManyToManyField(
                        related_name='host_templates', to='dcim.devicetype'
                    ),
                ),
                (
                    'groups',
                    models.ManyToManyField(
                        related_name='host_templates',
                        to='netbox_zabbix.zabbixhostgroup',
                    ),
                ),
                (
                    'locations',
                    models.ManyToManyField(
                        related_name='host_templates', to='dcim.location'
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='users.owner',
                    ),
                ),
                (
                    'platforms',
                    models.ManyToManyField(
                        related_name='host_templates', to='dcim.platform'
                    ),
                ),
                (
                    'regions',
                    models.ManyToManyField(
                        related_name='host_templates', to='dcim.region'
                    ),
                ),
                (
                    'roles',
                    models.ManyToManyField(
                        related_name='host_templates', to='dcim.devicerole'
                    ),
                ),
                (
                    'site_groups',
                    models.ManyToManyField(
                        related_name='host_templates', to='dcim.sitegroup'
                    ),
                ),
                (
                    'sites',
                    models.ManyToManyField(
                        related_name='host_templates', to='dcim.site'
                    ),
                ),
                ('tags', models.ManyToManyField(to='extras.tag')),
                (
                    'tenant_groups',
                    models.ManyToManyField(
                        related_name='host_templates', to='tenancy.tenantgroup'
                    ),
                ),
                (
                    'tenants',
                    models.ManyToManyField(
                        related_name='host_templates', to='tenancy.tenant'
                    ),
                ),
                (
                    'templates',
                    models.ManyToManyField(
                        related_name='host_templates', to='netbox_zabbix.zabbixtemplate'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Zabbix Host Template',
                'verbose_name_plural': 'Zabbix Host Templates',
                'ordering': ('name', 'id'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='zabbixhost',
            name='templates',
            field=models.ManyToManyField(
                related_name='hosts', to='netbox_zabbix.zabbixtemplate'
            ),
        ),
        migrations.AddConstraint(
            model_name='zabbixhostinterface',
            constraint=models.UniqueConstraint(
                fields=('zid',),
                name='netbox_zabbix_zabbixhostinterface_server_zid_unique',
            ),
        ),
        migrations.AddConstraint(
            model_name='zabbixhostinterfacesnmp',
            constraint=models.UniqueConstraint(
                fields=('interface',),
                name='netbox_zabbix_zabbixhostinterfacesnmp_interface_unique',
            ),
        ),
        migrations.AddConstraint(
            model_name='zabbixhostinterfacesnmp',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ('version__in', ['v1', 'v2c']),
                        ('context_name__isnull', True),
                        ('context_name', ''),
                        ('security_name__isnull', True),
                        ('security_name', ''),
                        ('security_level__isnull', True),
                        ('security_level', ''),
                        ('auth_protocol__isnull', True),
                        ('auth_protocol', ''),
                        ('auth_passphrase__isnull', True),
                        ('auth_passphrase', ''),
                        ('priv_protocol__isnull', True),
                        ('priv_protocol', ''),
                        ('priv_passphrase__isnull', True),
                        ('priv_passphrase', ''),
                    ),
                    models.Q(('version__in', ['v1', 'v2c']), _negated=True),
                    _connector='OR',
                ),
                name='zabbixhostinterfacesnmp_v1_v2c_fields_blank',
            ),
        ),
        migrations.AddConstraint(
            model_name='zabbixhostinterfacesnmp',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ('version', 'v3'),
                        ('community__isnull', True),
                        ('community', ''),
                        ('security_name__isnull', False),
                        models.Q(('security_name', ''), _negated=True),
                        ('security_level__isnull', False),
                        models.Q(('security_level', ''), _negated=True),
                    ),
                    models.Q(('version', 'v3'), _negated=True),
                    _connector='OR',
                ),
                name='zabbixhostinterfacesnmp_v3_fields',
            ),
        ),
        migrations.AddConstraint(
            model_name='zabbixhostinterfacesnmp',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ('security_level', 'noAuthnoPriv'),
                        ('auth_protocol__isnull', True),
                        ('auth_protocol', ''),
                        ('auth_passphrase__isnull', True),
                        ('auth_passphrase', ''),
                        ('priv_protocol__isnull', True),
                        ('priv_protocol', ''),
                        ('priv_passphrase__isnull', True),
                        ('priv_passphrase', ''),
                    ),
                    models.Q(
                        ('security_level', 'authNoPriv'),
                        ('auth_protocol__isnull', False),
                        models.Q(('auth_protocol', ''), _negated=True),
                        ('auth_passphrase__isnull', False),
                        models.Q(('auth_passphrase', ''), _negated=True),
                        ('priv_protocol__isnull', True),
                        ('priv_protocol', ''),
                        ('priv_passphrase__isnull', True),
                        ('priv_passphrase', ''),
                    ),
                    models.Q(
                        ('security_level', 'authPriv'),
                        ('auth_protocol__isnull', False),
                        models.Q(('auth_protocol', ''), _negated=True),
                        ('auth_passphrase__isnull', False),
                        models.Q(('auth_passphrase', ''), _negated=True),
                        ('priv_protocol__isnull', False),
                        models.Q(('priv_protocol', ''), _negated=True),
                        ('priv_passphrase__isnull', False),
                        models.Q(('priv_passphrase', ''), _negated=True),
                    ),
                    ('security_level__isnull', True),
                    ('security_level', ''),
                    _connector='OR',
                ),
                name='zabbixhostinterfacesnmp_securitylevel_fields',
            ),
        ),
        migrations.AddConstraint(
            model_name='zabbixserver',
            constraint=models.UniqueConstraint(
                fields=('name',), name='netbox_zabbix_zabbixserver_name_unique'
            ),
        ),
        migrations.AddConstraint(
            model_name='zabbixserver',
            constraint=models.UniqueConstraint(
                fields=('api_url',), name='netbox_zabbix_zabbixserver_api_url_unique'
            ),
        ),
        migrations.AddConstraint(
            model_name='zabbixproxygroup',
            constraint=models.UniqueConstraint(
                fields=('server', 'zid'),
                name='netbox_zabbix_zabbixproxygroup_server_zid_unique',
            ),
        ),
        migrations.AddConstraint(
            model_name='zabbixproxygroup',
            constraint=models.UniqueConstraint(
                fields=('server', 'name'),
                name='netbox_zabbix_zabbixproxygroup_server_name_unique',
            ),
        ),
        migrations.AddConstraint(
            model_name='zabbixproxy',
            constraint=models.UniqueConstraint(
                fields=('server', 'zid'),
                name='netbox_zabbix_zabbixproxy_server_zid_unique',
            ),
        ),
        migrations.AddConstraint(
            model_name='zabbixproxy',
            constraint=models.UniqueConstraint(
                fields=('server', 'name'),
                name='netbox_zabbix_zabbixproxy_server_name_unique',
            ),
        ),
        migrations.AddConstraint(
            model_name='zabbixhostgroup',
            constraint=models.UniqueConstraint(
                fields=('zid',), name='netbox_zabbix_zabbixhostgroup_server_zid_unique'
            ),
        ),
        migrations.AddConstraint(
            model_name='zabbixhostgroup',
            constraint=models.UniqueConstraint(
                fields=('name',),
                name='netbox_zabbix_zabbixhostgroup_server_name_unique',
            ),
        ),
        migrations.AddConstraint(
            model_name='zabbixtemplate',
            constraint=models.UniqueConstraint(
                fields=('server', 'zid'),
                name='netbox_zabbix_zabbixtemplate_server_zid_unique',
            ),
        ),
        migrations.AddConstraint(
            model_name='zabbixtemplate',
            constraint=models.UniqueConstraint(
                fields=('server', 'name'),
                name='netbox_zabbix_zabbixtemplate_server_name_unique',
            ),
        ),
        migrations.AddConstraint(
            model_name='zabbixhost',
            constraint=models.UniqueConstraint(
                fields=('server', 'zid'),
                name='netbox_zabbix_zabbixhost_server_zid_unique',
            ),
        ),
        migrations.AddConstraint(
            model_name='zabbixhost',
            constraint=models.UniqueConstraint(
                fields=('server', 'assigned_object_type', 'assigned_object_id'),
                name='netbox_zabbix_zabbixhost_server_assigned_object_unique',
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name='zabbixhost',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('assigned_object_type__isnull', False),
                    ('assigned_object_id__isnull', False),
                ),
                name='netbox_zabbix_zabbixhost_assigned_object_not_null',
                violation_error_message='The assigned object cannot be null',
            ),
        ),
    ]
